# Generated by Django 5.2.7 on 2025-12-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
            ],
            options={
                'db_table': 'asesores_comerciales',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'editoriales',
            },
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_modular', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instituciones_educativas',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('ADOPTADA', 'Adoptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador_colegio.asesorcomercial')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='cotizador_colegio.institucioneducativa')),
            ],
            options={
                'db_table': 'cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateField(auto_now_add=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adopcion', to='cotizador_colegio.cotizacion')),
            ],
            options={
                'db_table': 'adopciones',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('ENVIADO', 'Enviado a proveedor'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('adopcion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='cotizador_colegio.adopcion')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('grado', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('pvp_2026', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_proveedor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_proveedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='cotizador_colegio.editorial')),
            ],
            options={
                'db_table': 'productos',
                'unique_together': {('editorial', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_proveedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizador_colegio.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.producto')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_be', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc_proveedor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_proveedor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_ie', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('precio_ie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_ppff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilidad_ie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roi_ie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_venta', models.CharField(choices=[('FERIA', 'Feria'), ('CONSIGNA', 'Consignación'), ('PUNTO_DE_VENTA', 'Punto de Venta')], max_length=20)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizador_colegio.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.producto')),
            ],
            options={
                'db_table': 'detalle_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='DetalleAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_adoptada', models.PositiveIntegerField(default=0)),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizador_colegio.adopcion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.producto')),
            ],
            options={
                'db_table': 'detalles_adopcion',
            },
        ),
    ]
