# Generated by Django 5.2.7 on 2025-10-23 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_editorial', models.CharField(blank=True, max_length=150, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Asesor Comercial',
                'verbose_name_plural': 'Asesores Comerciales',
                'db_table': 'asesores_comerciales',
            },
        ),
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_modular', models.CharField(blank=True, max_length=50, null=True)),
                ('nivel_educativo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('director', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Institución Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
                'db_table': 'instituciones_educativas',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_completa', models.TextField()),
                ('tipo_inventario', models.CharField(blank=True, max_length=50, null=True)),
                ('soporte', models.CharField(blank=True, max_length=50, null=True)),
                ('pvp_2026_con_igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_venta', models.CharField(choices=[('FERIA', 'Feria'), ('CONSIGNA', 'Consignación'), ('PUNTO_DE_VENTA', 'Punto de Venta')], default='FERIA', max_length=20)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador_colegio.asesorcomercial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='cotizador_colegio.institucioneducativa')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_be', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_ie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_consigna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_coordinado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_ppff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desc_consigna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comision', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('utilidad_ie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roi_ie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roi_consigna', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizador_colegio.cotizacion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador_colegio.libro')),
            ],
            options={
                'verbose_name': 'Detalle de cotización',
                'verbose_name_plural': 'Detalles de cotización',
                'db_table': 'detalles_cotizacion',
            },
        ),
    ]
