# Generated by Django 5.2.7 on 2025-10-23 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotización'},
        ),
        migrations.AddField(
            model_name='asesorcomercial',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asesorcomercial',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('ADOPTADA', 'Adoptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='desc_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='precio_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='año_catalogo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adopcion', models.DateField(auto_now_add=True)),
                ('modalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_finales', models.TextField(blank=True, null=True)),
                ('firma_director', models.CharField(blank=True, max_length=150, null=True)),
                ('firma_asesor', models.CharField(blank=True, max_length=150, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='adopciones/')),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopcion', to='cotizador_colegio.cotizacion')),
            ],
            options={
                'verbose_name': 'Adopción',
                'verbose_name_plural': 'Adopciones',
                'db_table': 'adopciones',
            },
        ),
    ]
