# Generated by Django 5.2.7 on 2026-01-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0002_detalleadopcion_mes_lectura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
