# Generated by Django 5.2.7 on 2026-01-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0003_cotizacion_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
