# Generated by Django 5.2.7 on 2025-10-25 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0003_alter_cotizacion_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='cantidad_adoptada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='cotizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adopcion', to='cotizador_colegio.cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.asesorcomercial'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='cotizador_colegio.institucioneducativa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.libro'),
        ),
    ]
