# Generated by Django 5.2.7 on 2025-10-25 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0004_adopcion_cantidad_adoptada_alter_adopcion_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_adoptada', models.PositiveIntegerField(default=0)),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizador_colegio.adopcion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.libro')),
            ],
            options={
                'verbose_name': 'Detalle de Adopción',
                'verbose_name_plural': 'Detalles de Adopción',
                'db_table': 'detalles_adopcion',
            },
        ),
    ]
