# Generated by Django 5.2.7 on 2025-10-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0005_detalleadopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleadopcion',
            name='mes_lectura',
            field=models.CharField(blank=True, choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SETIEMBRE', 'Setiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], help_text='Mes en que se leerá este título (solo para plan lector)', max_length=20, null=True),
        ),
    ]
