# Generated by Django 5.2.7 on 2025-10-25 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0006_detalleadopcion_mes_lectura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador_colegio.asesorcomercial'),
        ),
    ]
