# Generated by Django 5.2.7 on 2025-10-26 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0007_alter_cotizacion_asesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleadopcion',
            name='mes_lectura',
            field=models.CharField(blank=True, choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SETIEMBRE', 'Setiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado', 'fecha'], name='cotizacione_estado_90a6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['numero_cotizacion'], name='cotizacione_numero__e967de_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['empresa', 'nivel', 'grado', 'area'], name='libros_empresa_1009a2_idx'),
        ),
    ]
