# Generated by Django 5.2.7 on 2025-10-27 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0008_alter_detalleadopcion_mes_lectura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopcion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='asesorcomercial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detalleadopcion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detallecotizacion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='institucioneducativa',
            options={},
        ),
        migrations.RemoveField(
            model_name='adopcion',
            name='cantidad_adoptada',
        ),
        migrations.AddField(
            model_name='adopcion',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('ENVIADO', 'Enviado a proveedor'), ('CONFIRMADO', 'Confirmado por proveedor'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adopcion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='cotizador_colegio.adopcion')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.libro')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizador_colegio.pedido')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
    ]
