# Generated by Django 5.2.7 on 2025-10-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0009_alter_adopcion_options_alter_asesorcomercial_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cotizacion',
            name='cotizacione_estado_90a6d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cotizacion',
            name='cotizacione_numero__e967de_idx',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='tipo_venta',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='tipo_venta',
            field=models.CharField(default='PV', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='desc_consigna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='desc_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_be',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='precio_proveedor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='utilidad_ie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='detallecotizacion',
            table='detalle_cotizacion',
        ),
    ]
