# Generated by Django 5.2.7 on 2025-10-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0010_remove_cotizacion_cotizacione_estado_90a6d9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
    ]
