# Generated by Django 5.2.7 on 2025-11-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador_colegio', '0011_cotizacion_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='tipo_venta',
            field=models.CharField(choices=[('FERIA', 'Feria'), ('CONSIGNA', 'Consignación'), ('PUNTO_DE_VENTA', 'Punto de Venta')], max_length=20),
        ),
    ]
