# Generated by Django 5.2.7 on 2026-01-29 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizador_colegio', '0004_adopcion_cantidad_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('KIT', 'Kit'), ('PACK', 'Pack'), ('COMBO', 'Combo')], default='KIT', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kit/Pack',
                'verbose_name_plural': 'Kits/Packs',
                'indexes': [models.Index(fields=['nombre', 'tipo', 'activo'], name='kit_kit_nombre_00752f_idx')],
            },
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kit.kit')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kit_items', to='cotizador_colegio.producto')),
            ],
            options={
                'verbose_name': 'Item de Kit',
                'verbose_name_plural': 'Items de Kit',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'producto'), name='uniq_kit_producto'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='chk_kititem_cantidad_gt0')],
            },
        ),
    ]
