# Generated by Django 5.2.7 on 2026-01-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='codigo_barra',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='kit',
            index=models.Index(fields=['codigo_barra'], name='kit_kit_codigo__e4f3bc_idx'),
        ),
    ]
