# Generated by Django 5.2.7 on 2026-01-23 01:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizador_colegio', '0004_adopcion_cantidad_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('PUNTO_VENTA', 'Punto de Venta'), ('FERIA', 'Feria'), ('CONSIGNA', 'Consignación')], default='PRINCIPAL', max_length=20)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_REMISION', 'Guía de Remisión'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito'), ('OTRO', 'Otro')], default='FACTURA', max_length=20)),
                ('numero_documento', models.CharField(max_length=60)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, default='')),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='almacen.almacen')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='cotizador_colegio.editorial')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
        migrations.CreateModel(
            name='IngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_detalle', to='cotizador_colegio.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Ingreso',
                'verbose_name_plural': 'Detalles de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('TRANSFERENCIA_SALIDA', 'Transferencia (Salida)'), ('TRANSFERENCIA_INGRESO', 'Transferencia (Ingreso)'), ('DEVOLUCION', 'Devolución'), ('AJUSTE_POS', 'Ajuste (+)'), ('AJUSTE_NEG', 'Ajuste (-)')], max_length=30)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_REMISION', 'Guía de Remisión'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=60)),
                ('entrada', models.PositiveIntegerField(default=0)),
                ('salida', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='almacen.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='cotizador_colegio.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('valorizado_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='almacen.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='cotizador_colegio.producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_REMISION', 'Guía de Remisión'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito'), ('OTRO', 'Otro')], default='GUIA_REMISION', max_length=20)),
                ('numero_documento', models.CharField(max_length=60)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='almacen.almacen')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='almacen.almacen')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_detalle', to='cotizador_colegio.producto')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.transferencia')),
            ],
            options={
                'verbose_name': 'Detalle de Transferencia',
                'verbose_name_plural': 'Detalles de Transferencia',
            },
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['numero_documento'], name='almacen_ing_numero__bb27f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['fecha_documento'], name='almacen_ing_fecha_d_0485bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingreso',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero_documento', 'proveedor'), name='uniq_ingreso_doc_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='ingresodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='chk_ing_det_cantidad_gte0'),
        ),
        migrations.AddConstraint(
            model_name='ingresodetalle',
            constraint=models.CheckConstraint(condition=models.Q(('costo_unitario__gte', 0)), name='chk_ing_det_costo_gte0'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['fecha'], name='almacen_mov_fecha_1a3067_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['tipo'], name='almacen_mov_tipo_b0f399_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['numero_documento'], name='almacen_mov_numero__92095c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('almacen', 'producto'), name='uniq_stock_almacen_producto'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['numero_documento'], name='almacen_tra_numero__e93b04_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['fecha_documento'], name='almacen_tra_fecha_d_13ef5d_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['estado'], name='almacen_tra_estado_72b8d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.CheckConstraint(condition=models.Q(('almacen_origen', models.F('almacen_destino')), _negated=True), name='chk_transfer_origen_destino_distintos'),
        ),
        migrations.AddConstraint(
            model_name='transferenciadetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='chk_trans_det_cantidad_gte0'),
        ),
    ]
