# Generated by Django 5.2.7 on 2026-01-23 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('cotizador_colegio', '0004_adopcion_cantidad_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='fecha_registro',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['tipo'], name='almacen_alm_tipo_c184b5_idx'),
        ),
        migrations.AddIndex(
            model_name='almacen',
            index=models.Index(fields=['activo'], name='almacen_alm_activo_68cfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['estado'], name='almacen_ing_estado_e5166b_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['created_at'], name='almacen_ing_created_572ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresodetalle',
            index=models.Index(fields=['producto'], name='almacen_ing_product_fa4cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['almacen', 'producto'], name='almacen_mov_almacen_e18f83_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['almacen', 'producto'], name='almacen_sto_almacen_a3ba5c_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['updated_at'], name='almacen_sto_updated_067ded_idx'),
        ),
        migrations.AddIndex(
            model_name='transferencia',
            index=models.Index(fields=['created_at'], name='almacen_tra_created_ec611b_idx'),
        ),
        migrations.AddIndex(
            model_name='transferenciadetalle',
            index=models.Index(fields=['producto'], name='almacen_tra_product_4ed04c_idx'),
        ),
    ]
