# Generated by Django 5.2.7 on 2026-01-24 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_rename_fecha_registro_ingreso_created_at_and_more'),
        ('cotizador_colegio', '0004_adopcion_cantidad_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ajuste', models.CharField(choices=[('POSITIVO', 'Aumenta Stock (+)'), ('NEGATIVO', 'Disminuye Stock (-)')], max_length=20)),
                ('motivo', models.CharField(choices=[('MERMA', 'Merma / Daño'), ('PERDIDA', 'Pérdida / Robo'), ('CONTEO', 'Diferencia por Conteo'), ('ERROR', 'Error Operativo'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_REMISION', 'Guía de Remisión'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito'), ('INVENTARIO', 'Inventario'), ('OTRO', 'Otro')], default='INVENTARIO', max_length=20)),
                ('numero_documento', models.CharField(blank=True, default='', max_length=60)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('observacion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ajuste de Stock',
                'verbose_name_plural': 'Ajustes de Stock',
            },
        ),
        migrations.CreateModel(
            name='AjusteStockDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Ajuste',
                'verbose_name_plural': 'Detalles de Ajuste',
            },
        ),
        migrations.RemoveIndex(
            model_name='almacen',
            name='almacen_alm_tipo_c184b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='almacen',
            name='almacen_alm_activo_68cfd1_idx',
        ),
        migrations.RemoveIndex(
            model_name='ingreso',
            name='almacen_ing_estado_e5166b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ingreso',
            name='almacen_ing_created_572ec0_idx',
        ),
        migrations.RemoveIndex(
            model_name='ingresodetalle',
            name='almacen_ing_product_fa4cf0_idx',
        ),
        migrations.RemoveIndex(
            model_name='movimientostock',
            name='almacen_mov_almacen_e18f83_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='almacen_sto_almacen_a3ba5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='stock',
            name='almacen_sto_updated_067ded_idx',
        ),
        migrations.RemoveIndex(
            model_name='transferencia',
            name='almacen_tra_created_ec611b_idx',
        ),
        migrations.RemoveIndex(
            model_name='transferenciadetalle',
            name='almacen_tra_product_4ed04c_idx',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_REMISION', 'Guía de Remisión'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito'), ('INVENTARIO', 'Inventario'), ('OTRO', 'Otro')], default='FACTURA', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_REMISION', 'Guía de Remisión'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito'), ('INVENTARIO', 'Inventario'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('GUIA_REMISION', 'Guía de Remisión'), ('BOLETA', 'Boleta'), ('NOTA_CREDITO', 'Nota de Crédito'), ('INVENTARIO', 'Inventario'), ('OTRO', 'Otro')], default='GUIA_REMISION', max_length=20),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='almacen.almacen'),
        ),
        migrations.AddField(
            model_name='ajustestock',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustestockdetalle',
            name='ajuste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='almacen.ajustestock'),
        ),
        migrations.AddField(
            model_name='ajustestockdetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_detalle', to='cotizador_colegio.producto'),
        ),
        migrations.AddIndex(
            model_name='ajustestock',
            index=models.Index(fields=['fecha_documento'], name='almacen_aju_fecha_d_b9a3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='ajustestock',
            index=models.Index(fields=['estado'], name='almacen_aju_estado_83386a_idx'),
        ),
        migrations.AddIndex(
            model_name='ajustestock',
            index=models.Index(fields=['numero_documento'], name='almacen_aju_numero__e373fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='ajustestockdetalle',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='chk_ajuste_det_cantidad_gte0'),
        ),
    ]
