# Generated by Django 5.2.7 on 2026-01-27 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_ajustestock_ajustestockdetalle_and_more'),
        ('cotizador_colegio', '0004_adopcion_cantidad_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='uniq_stock_almacen_producto',
        ),
        migrations.AddField(
            model_name='stock',
            name='punto_reposicion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.almacen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizador_colegio.producto'),
        ),
    ]
