# Generated by Django 5.2.7 on 2026-01-27 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_stock_options_and_more'),
        ('cotizador_colegio', '0004_adopcion_cantidad_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='almacen.almacen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='cotizador_colegio.producto'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('almacen', 'producto'), name='uniq_stock_almacen_producto'),
        ),
    ]
