# Generated by Django 5.2.7 on 2026-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_alter_stock_almacen_alter_stock_producto_and_more'),
        ('cotizador_colegio', '0004_adopcion_cantidad_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('stock_minimo__gte', 0)), name='chk_stock_minimo_gte0'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('punto_reposicion__gte', 0)), name='chk_punto_reposicion_gte0'),
        ),
    ]
